// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-api-base'
  | 'pref-api-key'
  | 'pref-enabled'
  | 'pref-help'
  | 'pref-model'
  | 'pref-system-prompt'
  | 'pref-target-language'
  | 'pref-test-connection'
  | 'pref-title'
  | 'prefs-title'
  | 'toolbar-translation-toggle';
